name: Docker Image CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-[0-9]+ # Match tags like v21.4.0-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract metadata for Docker
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            smartassist/gocd-agent-ruby3.1
          flavor: |
            latest=false
          tags: |
            type=match,pattern=(v\d+.\d+.\d+)
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
